### ISSUE TITLE
UPDATE Version: gradle-wrapper.properties - gradle-5.3-all.zip

### ISSUE THREAD

**Issue by AMartsinkevich** [suhocki/starlord#49]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by AMartsinkevich** [comment]
distributionUrl=https\://services.gradle.org/distributions/gradle-5.3-all.zip

**Comment by suhocki** [comment]
см #48
